### ISSUE TITLE
dev tools break completely with preact-router

### ISSUE THREAD

**Issue by AEnterprise** [preactjs/preact-devtools#38] opened 2019-12-10 09:24 UTC
using preact router and routing around the component view breaks in various ways:

* components missing in the tree, namely the router itself and everything on the same level that comes after it. disabling the DOM node filter and re-enabling this makes the router and other missing components show up
![2019-12-10_10-03-05](https://user-images.githubusercontent.com/5206666/70514621-4cdca780-1b34-11ea-8513-efbc9cd9d377.gif)

* after using the workaround above to make the router visible the router contents are not shown, it just shows ``async`` with the route properties and a function state that i assume is how it loads in the routed component
![image](https://user-images.githubusercontent.com/5206666/70515205-3f73ed00-1b35-11ea-9548-c6b78cd47f05.png)

something that might be related to preact-router or not, i honestly can't tell:
* delayed updates of components in routers can sometimes just send it into a connecting state, waiting for nodes to load that are not loaded, the first set of servers instantly as can be served from the api over the websocket super fast, however the 2nd set comes from an external api so takes longer to load in. yet every time this second set loads it goes into this ``connected, waiting for nodes to load...`` state
![2019-12-10_10-14-20](https://user-images.githubusercontent.com/5206666/70516102-acd44d80-1b36-11ea-93bd-50a3cbda9f30.gif)

![image](https://user-images.githubusercontent.com/5206666/70515067-ffad0580-1b34-11ea-8162-c4da1ba4841c.png)

* however the above scenario doesn't always happen, sometimes it does not go into the loading state, it just nukes everything but the top 2 elements from view, disabling and re-enabling a filter like with the routers makes it show things again
![image](https://user-images.githubusercontent.com/5206666/70515377-895cd300-1b35-11ea-92d8-0a8cd4e05948.png)

* yet on other pages that regularly update this does not occur at all

code repo: https://github.com/gearbot/Dashboard

i'll look to deploy it to staging later today or tomorrow for demo repro case as most of these pages need the api connected to work

**Comment by developit** [comment] 2019-12-10 14:34
I'm inclined to think this is more related to preact-cli's `AsyncComponent` than it is to `preact-router`.

**Comment by marvinhagemeister** [comment] 2020-01-24 22:59
The current release `0.1.2` should fix this. It's already out on Firefox, but it's been in the review queue in Chrome for days now...

**Comment by pmkroeker** [comment] 2020-02-06 21:13
I think a similar thing happens when using wouter-preact.
![image](https://user-images.githubusercontent.com/10147685/73978984-39ef1500-48e2-11ea-9ef1-fffde6a225e0.png).

Not sure if this is related to wouter or the dev-tools though. Hopefully this is resolved with the pending release (on chrome)

**Comment by marvinhagemeister** [comment] 2020-02-07 08:45
@pmkroeker the chrome version got approved a few days back. Do you happen to have a repo/sandbox with the issue? I'd love to take a look at that :+1:

**Comment by pmkroeker** [comment] 2020-02-07 15:29
Hmm, in CodeSandbox it seems to work as intended.

[Reproduction](https://codesandbox.io/s/sad-morse-jzdl2)

I think it may be a webpack config issue. I'll investigate the issue. Could it potentially be due to using `Suspense`?

**Comment by marvinhagemeister** [comment] 2020-03-27 07:48
Good news: Just tried to reproduce this issue again with the latest version of the devtools extension (0.2.0, will be up in Chrome Webstore shortly) and I can't reproduce the error with the linked codesandboxes anymore :tada:

**Closed by marvinhagemeister** 2020-03-27 07:48 UTC
